apiVersion: training.eduk8s.io/v1alpha1
kind: Workshop
metadata:
  name: lab-jupyter-on-k8s-01
spec:
  vendor: eduk8s.io
  title: "Jupyter on Kubernetes #1"
  description: A workshop exploring deployment of Jupyter notebooks locally and to Kubernetes
  url: https://github.com/jupyter-on-kubernetes/lab-jupyter-on-k8s-01
  content: github.com/jupyter-on-kubernetes/lab-jupyter-on-k8s-01
  duration: 30m
  session:
    budget: large
    applications:
      console:
        enabled: true
      terminal:
        enabled: true
        layout: split
    ingresses:
    - name: local-8888
      port: 8888
